import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@cobypear/nextjs-kit/dist/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Header navItems={[{ href: "/", linkText: "Home" }]} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
